# Generated by Django 4.1.13 on 2024-04-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divisi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departemen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_departemen', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=20)),
                ('kode_departemen', models.CharField(max_length=100)),
                ('divisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisi_departemen', to='divisi.divisi')),
            ],
        ),
    ]
