# Generated by Django 4.1.13 on 2024-03-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lampiran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_lampiran", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="event_files/")),
            ],
        ),
    ]
