# Generated by Django 4.1.13 on 2024-04-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Divisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_divisi', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=20)),
                ('kode_divisi', models.CharField(max_length=100)),
            ],
        ),
    ]
